version: '3.7'

volumes:
  prometheus_data: {}
  grafana_data: {}

networks:
  observability:
    driver: "bridge"

services:
  initiator:
    image: observability/initiator
    expose:
      - "8081"
    ports:
      - "8081:8081"
    networks:
      - observability

  translator:
    image: observability/translator
    expose:
      - "8085"
    ports:
      - "8085:8085"
    networks:
      - observability

  lightProcessor:
    image: observability/light
    expose:
      - "8082"
    ports:
      - "8082:8082"
    depends_on:
      - "translator"
    networks:
      - observability

  mediumProcessor:
    image: observability/medium
    expose:
      - "8083"
    ports:
      - "8083:8083"
    depends_on:
      - "translator"
    networks:
      - observability

  heavyProcessor:
    image: observability/heavy
    expose:
      - "8084"
    ports:
      - "8084:8084"
    depends_on:
      - "translator"
    networks:
      - observability

  prometheus:
    image: prom/prometheus
    ports:
      - "9000:9000"
    expose:
      - 9090
    volumes:
      - /Users/user/dev/gs-spring-boot/initial/docker/prometheus.yml:/etc/prometheus/prometheus.yml
      - prometheus_data:/prometheus
    restart: unless-stopped
    networks:
      - observability

  grafana:
    image: grafana/grafana
    ports:
      - "3000:3000"
    volumes:
      - grafana_data:/var/lib/grafana
      - /Users/user/dev/gs-spring-boot/initial/docker/grafana:/etc/grafana/provisioning
    restart: unless-stopped
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=admin
    networks:
      - observability
