apiVersion: v1
kind: Secret
metadata:
  name: kiali
  namespace: dts-poc
  labels:
    app: kiali
    chart: kiali
    heritage: Tiller
    release: istio
type: Opaque
data:
  username: YWRtaW4=   # admin
  passphrase: YWRtaW4= # admin