apiVersion: v1
kind: Service
metadata:
  name: grafana
  namespace: dts-poc
  annotations:
  labels:
    app: grafana
    chart: grafana
    heritage: Tiller
    release: istio
spec:
  type: ClusterIP
  ports:
    - port: 3000
      targetPort: 3000
      protocol: TCP
      name: http
  selector:
    app: grafana