apiVersion: v1
kind: Service
metadata:
  name: kiali
  namespace: dts-poc
  labels:
    app: kiali
    chart: kiali
    heritage: Tiller
    release: istio
spec:
  ports:
    - name: http-kiali
      protocol: TCP
      port: 20001
  selector:
    app: kiali