apiVersion: v1
kind: ServiceAccount
metadata:
  name: istio-egressgateway-service-account
  namespace: dts-poc
  labels:
    app: istio-egressgateway
    chart: gateways
    heritage: Tiller
    release: istio