apiVersion: 1

datasources:
  - name: Prometheus
    type: prometheus
    access: proxy
    url: http://prometheus:9090
    basicAuth: false
    isDefault: true
    editable: true

  - name: Elastic
    type: elasticsearch
    access: proxy
    url: http://elastic:9200
    basicAuth: false
    isDefault: false
    editable: true
