apiVersion: policy/v1beta1
kind: PodDisruptionBudget
metadata:
  name: istio-citadel
  namespace: dts-poc
  labels:
    app: security
    chart: security
    heritage: Tiller
    release: istio
    istio: citadel
spec:

  minAvailable: 1
  selector:
    matchLabels:
      app: security
      release: istio
      istio: citadel