---
apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: issuers.certmanager.k8s.io
  labels:
    app: certmanager
    chart: certmanager
    heritage: Tiller
    release: istio
  annotations:
    "helm.sh/resource-policy": keep
spec:
  group: certmanager.k8s.io
  versions:
    - name: v1alpha1
      served: true
      storage: true
  names:
    kind: Issuer
    plural: issuers
  scope: Namespaced