apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: istio-security-post-install-dts-poc
  labels:
    app: security
    chart: security
    heritage: Tiller
    release: istio
rules:
  - apiGroups: ["authentication.istio.io"] # needed to create default authn policy
    resources: ["*"]
    verbs: ["*"]
  - apiGroups: ["networking.istio.io"] # needed to create security destination rules
    resources: ["*"]
    verbs: ["*"]
  - apiGroups: ["admissionregistration.k8s.io"]
    resources: ["validatingwebhookconfigurations"]
    verbs: ["get"]
  - apiGroups: ["extensions", "apps"]
    resources: ["deployments", "replicasets"]
    verbs: ["get", "list", "watch"]