global:
  scrape_interval:     10s
  evaluation_interval: 10s

scrape_configs:
  - job_name: 'observability'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['english:8091','spanishProcessor:8082','italianProcessor:8083','germanProcessor:8084','translator:8085']

  - job_name: 'prometheus'
    static_configs:
      - targets: ['prometheus:9090']

  - job_name: 'docker'

    static_configs:
      - targets: ['docker.for.mac.host.internal:9323']
