---
apiVersion: v1
kind: ConfigMap
metadata:
  name: app-config
  namespace: translator-app
  labels:
    app: translator-app
data:
  spring.zipkin.baseUrl: http://zipkin:9411/
  spring.kafka.bootstrap.servers: kafka.kafka.svc.cluster.local:29092
  kafka.bootstrap.servers: kafka.kafka.svc.cluster.local:29092
  kafka.key.serializer: org.apache.kafka.common.serialization.LongSerializer
  kafka.value.serializer: org.apache.kafka.common.serialization.StringSerializer
  kafka.key.deserializer: org.apache.kafka.common.serialization.LongDeserializer
  kafka.value.deserializer: org.apache.kafka.common.serialization.StringDeserializer
  kafka.acks: all
  translator.url: http://translator/translate
  ZIPKIN_SENDER_TYPE: HTTP
  ZIPKIN_HTTP_ENDPOINT: http://zipkin:9411/api/v2/spans