apiVersion: apps/v1
kind: Deployment
metadata:
  name: spanish
  namespace: translator-app
  labels:
    app: translator-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: spanish
  template:
    metadata:
      labels:
        app: spanish
    spec:
      containers:
        - name: spanish
          image: dts/spanish
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8082
          envFrom:
            - configMapRef:
                name: app-config
          env:
            - name: SERVER_PORT
              value: "8082"

            - name: kafka.client.id
              value: spanish

            - name: zipkin.service.name
              value: SpanishProcessor

            - name: kafka.consumer.group.id
              value: spanish

            - name: translator.target
              value: ES
---
apiVersion: v1
kind: Service
metadata:
  namespace: translator-app
  name: spanish
  labels:
    app: translator-app
spec:
  type: ClusterIP
  selector:
    app: spanish
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8082