apiVersion: v1
kind: ConfigMap
metadata:
  name: prometheus
  namespace: dts-poc
  labels:
    app: prometheus
    chart: prometheus
    heritage: Tiller
    release: istio
data:
  prometheus_file: '../prometheus/prometheus.yml'
