apiVersion: v1
kind: ConfigMap
metadata:
  name: prometheus
  namespace: istio-dts
  labels:
    app: prometheus
    chart: prometheus
    heritage: Tiller
    release: istio
data:
  prometheus_file: 'prometheus.yml'
